migration to plasma 6

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,11 +1,17 @@
 #!/bin/bash
-# Version 5
+# Version 6 - Plasma 6
 
 # This script detects if the widget is already installed.
 # If it is, it will use --upgrade instead and restart plasmashell.
 
-packageNamespace=`kreadconfig5 --file="$PWD/package/metadata.desktop" --group="Desktop Entry" --key="X-KDE-PluginInfo-Name"`
-packageServiceType=`kreadconfig5 --file="$PWD/package/metadata.desktop" --group="Desktop Entry" --key="X-KDE-ServiceTypes"`
+# Read plugin ID from metadata.json
+packageNamespace=$(grep -oP '"Id"\s*:\s*"\K[^"]+' "$PWD/package/metadata.json" 2>/dev/null)
+if [ -z "$packageNamespace" ]; then
+	echo "Error: Could not read Id from package/metadata.json"
+	exit 1
+fi
+
+packageServiceType="Plasma/Applet"
 restartPlasmashell=false
 
 for arg in "$@"; do
@@ -17,31 +23,26 @@ for arg in "$@"; do
 done
 
 isAlreadyInstalled=false
-kpackagetool5 --type="${packageServiceType}" --show="$packageNamespace" &> /dev/null
+kpackagetool6 --type="${packageServiceType}" --show="$packageNamespace" &> /dev/null
 if [ $? == 0 ]; then
 	isAlreadyInstalled=true
 fi
 
-### metadata.desktop => metadata.json
-if command -v desktoptojson &> /dev/null ; then
-	genOutput=`desktoptojson --serviceType="plasma-applet.desktop" -i "$PWD/package/metadata.desktop" -o "$PWD/package/metadata.json"`
-	if [ "$?" != "0" ]; then
-		exit 1
-	fi
-	# Tabify metadata.json
-	sed -i '{s/ \{4\}/\t/g}' "$PWD/package/metadata.json"
-fi
-
 if $isAlreadyInstalled; then
-	# Eg: kpackagetool5 -t "Plasma/Applet" -u package
-	kpackagetool5 -t "${packageServiceType}" -u package
+	# Eg: kpackagetool6 -t "Plasma/Applet" -u package
+	kpackagetool6 -t "${packageServiceType}" -u package
 	restartPlasmashell=true
 else
-	# Eg: kpackagetool5 -t "Plasma/Applet" -i package
-	kpackagetool5 -t "${packageServiceType}" -i package
+	# Eg: kpackagetool6 -t "Plasma/Applet" -i package
+	kpackagetool6 -t "${packageServiceType}" -i package
 fi
 
 if $restartPlasmashell; then
-	killall plasmashell
-	kstart5 plasmashell
+	# For Plasma 6, use systemctl to restart plasmashell
+	if command -v systemctl &> /dev/null && systemctl --user is-active plasma-plasmashell.service &> /dev/null; then
+		systemctl --user restart plasma-plasmashell.service
+	else
+		killall plasmashell
+		kstart plasmashell &
+	fi
 fi
